# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [2]:
# Given:
def same(list1):
    if list1[0] == list1[-1]:
        print("result is True")
    else:
        print("result is False")
    
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

same(numbers_x)
# Expected Output:
same(numbers_y)
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False

result is True
result is False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [13]:
#code here
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array((6, 7, 8, 9, 4))
print("The element vise sum is:  " , arr1+arr2)
print("The element vise product is: ", arr1*arr2)

The element vise sum is:   [ 7  9 11 13  9]
The element vise product is:  [ 6 14 24 36 20]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [43]:
#code here
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
result = np.reshape(arr1, (3,4))
print(result)
arr_2 = np.array([[1,2],[3,4]])
arr_3 = np.array([[5,6]])
print(np.concatenate((arr1, arr2), axis = 0))
print(np.concatenate((arr_2, arr_3.T), axis = 1))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12  6  7  8  9  4]
[[1 2 5]
 [3 4 6]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [45]:
#Code here
print("Welcome to meri pyaara shopping store!! :)")
shopping_cart = []
available_products = {1:"scented candles", 2:"markers", 3:"fairy lights", 4:"green tea", 5:"body mists", 6:"coke"}

while True:
    print(available_products)
    choice = input("Please enter the number corresponding to the desired product: ")
    if choice == "q" or choice == "Q":
        break
    shopping_cart.append(available_products[int(choice)])
    if int(choice) > 6:
        print("Choice out of range!!")
        continue
    print("")
    print(available_products[int(choice)], " successfully added to your shopping cart!!")
    print("")
print("Your shopping cart ", shopping_cart)
print("Goodbye!!")

Welcome to meri pyaara shopping store!! :)
{1: 'scented candles', 2: 'markers', 3: 'fairy lights', 4: 'green tea', 5: 'body mists', 6: 'coke'}
Please enter the number corresponding to the desired product: 3

fairy lights  successfully added to your shopping cart!!

{1: 'scented candles', 2: 'markers', 3: 'fairy lights', 4: 'green tea', 5: 'body mists', 6: 'coke'}
Please enter the number corresponding to the desired product: 1

scented candles  successfully added to your shopping cart!!

{1: 'scented candles', 2: 'markers', 3: 'fairy lights', 4: 'green tea', 5: 'body mists', 6: 'coke'}
Please enter the number corresponding to the desired product: 5

body mists  successfully added to your shopping cart!!

{1: 'scented candles', 2: 'markers', 3: 'fairy lights', 4: 'green tea', 5: 'body mists', 6: 'coke'}
Please enter the number corresponding to the desired product: q
Your shopping cart  ['fairy lights', 'scented candles', 'body mists']
Goodbye!!


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [55]:
#code here
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
def classify_emails(emails):
    important = []
    promotions = []
    spam = []
    for x in emails:
        tokens = word_tokenize(x)
        for token in tokens:
            token = token.lower()
            if "important" == token or "importance" == token:
                important.append(x)
            elif "promotion" == token or "promotions" == token:
                promotions.append(x)
            elif "spam" == token:
                spam.append(x)
    return important, promotions, spam
mails = ["Hello I am important", "mein promotion email hun", "mein virus hun"]
l1, l2, l3 = classify_emails(mails)
print(l1, l2, l3)

['Hello I am important'] ['mein promotion email hun'] []


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [62]:
#code here
dictionary = {'hello': 'hola', 'goodbye': 'adiós','thank you': 'gracias','please': 'por favor','yes': 'sí','no': 'no','friend': 'amigo/amiga','family': 'familia','love': 'amor','peace': 'paz','water': 'agua','food': 'comida','house': 'casa','time': 'tiempo','work': 'trabajo','school': 'escuela','money': 'dinero','happy': 'feliz','sad': 'triste','beautiful': 'hermoso/hermosa'}
while True:  
    print("Enter 0 to exit")
    word = input("Please enter an english word: ")
    if word == "0":
        break
    if word in dictionary.keys():
        print("")
        print(dictionary[word])
    else:
        print("Translation is not available!")
    print("")

Enter 0 to exit
Please enter an english word: hello

hola

Enter 0 to exit
Please enter an english word: please

por favor

Enter 0 to exit
Please enter an english word: friend

amigo/amiga

Enter 0 to exit
Please enter an english word: yes

sí

Enter 0 to exit
Please enter an english word: no

no

Enter 0 to exit
Please enter an english word: 0


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [69]:
import pandas as pd
url = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
data = pd.read_csv(url, sep = ",", encoding = "utf-8")

In [70]:
data

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [71]:
print("Total global sales of all games are ", data["Global_Sales"].sum())

Total global sales of all games are  8920.44


In [74]:
highest = data[data["Global_Sales"] == data["Global_Sales"].max()]
highest["Name"]

0    Wii Sports
Name: Name, dtype: object

In [76]:
avg_NA = data["NA_Sales"].mean()
avg_EU = data["EU_Sales"].mean()
avg_JP = data["JP_Sales"].mean()
print("Average Sales of NA are ", avg_NA)
print("Average Sales of EU are ", avg_EU)
print("Average Sales of JP are ", avg_JP)

Average Sales of NA are  0.26466742981082064
Average Sales of EU are  0.14665200626581515
Average Sales of JP are  0.077781660441017


In [80]:
datanew = data.sort_values(by = "Global_Sales", ascending = False)
datanew["Genre"][:5]

0          Sports
1        Platform
2          Racing
3          Sports
4    Role-Playing
Name: Genre, dtype: object

In [101]:
genre_grouped = data.groupby("Genre")
genres = data["Genre"].unique()
genres
NA_values = {}
for genre in genres:
    temp = genre_grouped.get_group(genre)
    NA_values[genre] = temp["NA_Sales"].sum()
    print("Total Sales for", genre, " in NA are ", temp["NA_Sales"].sum())
    print("Total Sales for", genre, " in EU are ", temp["EU_Sales"].sum())    
    print("Total Sales for", genre, " in JP are ", temp["JP_Sales"].sum())  
    print("")

Total Sales for Sports  in NA are  683.35
Total Sales for Sports  in EU are  376.85
Total Sales for Sports  in JP are  135.37

Total Sales for Platform  in NA are  447.05
Total Sales for Platform  in EU are  201.63000000000002
Total Sales for Platform  in JP are  130.77

Total Sales for Racing  in NA are  359.41999999999996
Total Sales for Racing  in EU are  238.39000000000001
Total Sales for Racing  in JP are  56.68999999999999

Total Sales for Role-Playing  in NA are  327.28
Total Sales for Role-Playing  in EU are  188.05999999999997
Total Sales for Role-Playing  in JP are  352.31

Total Sales for Puzzle  in NA are  123.78
Total Sales for Puzzle  in EU are  50.779999999999994
Total Sales for Puzzle  in JP are  57.309999999999995

Total Sales for Misc  in NA are  410.24
Total Sales for Misc  in EU are  215.98000000000002
Total Sales for Misc  in JP are  107.76

Total Sales for Shooter  in NA are  582.6
Total Sales for Shooter  in EU are  313.27000000000004
Total Sales for Shooter  in 

In [126]:
l1 = np.array(list(NA_values))
l2 = np.array(list(NA_values.values()))
l1[l2.argmax()]

'Action'

In [90]:
data.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [91]:
datanew["Platform"][:3]

0    Wii
1    NES
2    Wii
Name: Platform, dtype: object

In [95]:
for genre in genres:
    temp = genre_grouped.get_group(genre)
    print("Market Share of", genre, " is ", (temp["Global_Sales"].sum()/data["Global_Sales"].sum())*100, "%") 
    print("")

Market Share of Sports  is  14.920003945993695 %

Market Share of Platform  is  9.319831757177896 %

Market Share of Racing  is  8.206321661263345 %

Market Share of Role-Playing  is  10.396011855917422 %

Market Share of Puzzle  is  2.7459407831900666 %

Market Share of Misc  is  9.07982117474026 %

Market Share of Shooter  is  11.629134885723126 %

Market Share of Simulation  is  4.396644111725431 %

Market Share of Action  is  19.63109443031958 %

Market Share of Fighting  is  5.0323750846370805 %

Market Share of Adventure  is  2.6796884458614145 %

Market Share of Strategy  is  1.963131863450682 %



In [138]:
print("The correlation of the two columns is ", data["NA_Sales"].corr(data["EU_Sales"]))

The correlation of the two columns is  0.7677267483702636
